"""설정 패키지"""

from dotenv import load_dotenv
load_dotenv()  # .env 파일이 있으면 환경변수로 로딩 (API, Celery 공통)

from .settings import (
    PROJECT_ROOT, DATA_DIR, MODEL_DIR,
    INPUT_DIR, OUTPUT_RAW_DIR, OUTPUT_PROCESSED_DIR, FINISHED_DIR, ERROR_DIR, LOG_DIR,
    TEXT_MAX_CHARS, TABLE_MAX_CHARS, CHUNK_MIN_CHARS,
    FIXED_WINDOW_SIZE, FIXED_OVERLAP_SIZE,
    OCR_MIN_FILE_SIZE, OCR_MIN_IMAGE_WIDTH, OCR_MIN_IMAGE_HEIGHT,
    OCR_FIGURE_MIN_WIDTH, OCR_FIGURE_MIN_HEIGHT,
    OCR_MAX_ASPECT_RATIO, OCR_MAX_IMAGE_DIMENSION,
    OCR_MIN_PIXEL_STDDEV,
    OCR_MIN_TEXT_LENGTH,
    StatusCode,
)
from .database import SessionLocal, get_db, task_session, engine, Base
from .qdrant import QDRANT_CONFIG, LLM_CONFIG, BM25_CONFIG, RERANKER_CONFIG, EMBEDDING_CONFIG

__all__ = [
    "PROJECT_ROOT", "DATA_DIR", "MODEL_DIR",
    "INPUT_DIR", "OUTPUT_RAW_DIR", "OUTPUT_PROCESSED_DIR", "FINISHED_DIR", "ERROR_DIR", "LOG_DIR",
    "TEXT_MAX_CHARS", "TABLE_MAX_CHARS", "CHUNK_MIN_CHARS",
    "FIXED_WINDOW_SIZE", "FIXED_OVERLAP_SIZE",
    "OCR_MIN_FILE_SIZE", "OCR_MIN_IMAGE_WIDTH", "OCR_MIN_IMAGE_HEIGHT",
    "OCR_FIGURE_MIN_WIDTH", "OCR_FIGURE_MIN_HEIGHT",
    "OCR_MAX_ASPECT_RATIO", "OCR_MAX_IMAGE_DIMENSION",
    "OCR_MIN_PIXEL_STDDEV",
    "OCR_MIN_TEXT_LENGTH",
    "StatusCode",
    "SessionLocal", "get_db", "task_session", "engine", "Base",
    "QDRANT_CONFIG", "LLM_CONFIG", "BM25_CONFIG", "RERANKER_CONFIG", "EMBEDDING_CONFIG",
]
